import MuiThemeRegistry from "src/components/MuiThemeRegistry/ThemeRegistry";
import { TrpcProvider } from "src/components/TrpcProvider";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <TrpcProvider>
          <MuiThemeRegistry>{children}</MuiThemeRegistry>
        </TrpcProvider>
      </body>
    </html>
  );
}
