import { ThemeProvider } from "src/providers/ThemeProvider";
import { StoreProvider } from "src/providers/StoreProvider";
import { TrpcProvider } from "src/providers/TrpcProvider";
import { TRPCApiErrorProvider } from "src/ui/errors/api";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <TRPCApiErrorProvider>
          <TrpcProvider>
            <StoreProvider>
              <ThemeProvider>{children}</ThemeProvider>
            </StoreProvider>
          </TrpcProvider>{" "}
        </TRPCApiErrorProvider>
      </body>
    </html>
  );
}
