import ThemeRegistry from "src/components/ThemeRegistry/ThemeRegistry";
import { TrpcProvider } from "src/components/TrpcProvider";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <TrpcProvider>
          <ThemeRegistry>{children}</ThemeRegistry>
        </TrpcProvider>
      </body>
    </html>
  );
}
