export enum TweetsSearchUserField {
  CreatedAt = 'created_at',
  Description = 'description',
  Entities = 'entities',
  Id = 'id',
  Location = 'location',
  Name = 'name',
  PinnedTweetId = 'pinned_tweet_id',
  ProfileImageUrl = 'profile_image_url',
  Protected = 'protected',
  PublicMetrics = 'public_metrics',
  Url = 'url',
  Username = 'username',
  Verified = 'verified',
  Withheld = 'withheld',
}
